### ISSUE TITLE
RCode\_for\_RAPBEE_model.R 文件中的数据文件找不到

### ISSUE THREAD

**Issue by donaldyangsunvalley** [zhiyulee-RUC/ReviewSpamDet#1]
牛人，你好。RCode\_for\_RAPBEE_model.R 文件中的数据文件找不到，在代码中引用的“data/*.txt”没有找到，请问在哪可以找到？

**Comment by zhiyulee-RUC** [comment]
代码中引用的“data/*.txt” 的文件实际上就是项目里面的 .xlsx 文件，需要更换一下格式读取；
